version: '3.8'

services:
  db:
    image: postgres:13
    container_name: sprint_review_db
    restart: always
    env_file:
      - ./apps/backend/.env
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - sprintreview_db_folder:/var/lib/postgresql/data

volumes:
  sprintreview_db_folder: